version: 2
updates:
  - package-ecosystem: "npm"
    assignees:
      - "yanhao98"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    assignees:
      - "yanhao98"
    directory: "/"
    schedule:
      interval: "daily"
