name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ['main', 'vite']

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main
      - run: pnpm lint
      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
        with:
          commit-message: 'chore: apply automated updates'
