name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main
      - run: pnpm lint
      - run: pnpm test:types
      - run: pnpm build
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
