name: CI

on:
  push:
    branches:
      - main
      - vite
  pull_request:
    branches:
      - main
      - vite

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: yanhao98/composite-actions/setup-node-environment@main
      - run: pnpm lint
      - run: pnpm type-check
      - run: pnpm build
      - run: pnpx publint # https://publint.dev/
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
